schema_version = 1

[defaults]
ttl = "12h"

[capture-replicate-deploy]
deploy_regions = ["us-east"]
replication_groups = ["country_us"]
# region_policy_file = "policy/staging-region-policy.toml"
source_image = "linode/alpine3.23"
type = "g6-nanode-1"
firewall_id = 12345
