from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from linode_image_lab.region_policy import (
    generate_region_policy_artifact,
    generated_country_capability_group_name,
    generated_region_groups,
    load_policy,
    serialize_validation_report,
    validate_region_policy_artifact,
)


class FakeRegionClient:
    def __init__(self, regions: list[dict[str, object]]) -> None:
        self.regions = regions

    def list_regions(self) -> list[dict[str, object]]:
        return list(self.regions)


class RegionPolicyTests(unittest.TestCase):
    def test_checked_in_policy_contains_operator_geo_groups(self) -> None:
        policy_path = Path(__file__).resolve().parents[2] / "policy" / "region-policy.toml"
        policy = load_policy(policy_path)

        groups = policy["groups"]
        self.assertEqual(
            groups["geo_americas"]["regions"],
            [
                "br-gru",
                "ca-central",
                "us-central",
                "us-east",
                "us-iad",
                "us-iad-2",
                "us-lax",
                "us-mia",
                "us-ord",
                "us-sea",
                "us-southeast",
                "us-west",
            ],
        )
        self.assertEqual(groups["geo_europe_image_replication"]["regions"], ["fr-par", "gb-lon"])
        self.assertEqual(groups["geo_apac_north"]["regions"], ["ap-northeast", "jp-osa", "jp-tyo-3"])
        self.assertEqual(
            policy["provider_regions"]["jp-tyo-3"]["capabilities"],
            [
                "ACLP Logs Datacenter LKE-E",
                "Backups",
                "Block Storage",
                "Block Storage Encryption",
                "Cloud Firewall",
                "Disk Encryption",
                "GPU Linodes",
                "Kubernetes",
                "Linode Interfaces",
                "Linodes",
                "Maintenance Policy",
                "Managed Databases",
                "Metadata",
                "NodeBalancers",
                "Object Storage",
                "Placement Group",
                "Premium Plans",
                "StackScripts",
                "VPCs",
                "Vlans",
            ],
        )
        self.assertEqual(policy["generated_groups"]["country_jp_object_storage"]["regions"], ["jp-tyo-3"])
        self.assertNotIn("country_jp_image_replication", policy["generated_groups"])
        self.assertNotIn("geo_apac_north_image_replication", groups)
        self.assertNotIn("geo_india_image_replication", groups)
        self.assertNotIn("geo_oceania_image_replication", groups)

    def test_generation_is_deterministic_and_normalizes_capabilities(self) -> None:
        client = FakeRegionClient(
            [
                {
                    "region": "us-sea",
                    "capabilities": ["Object Storage", "Linodes", "Linodes", "", 123],
                    "country": "us",
                },
                {
                    "region": "gb-lon",
                    "capabilities": [" Linodes ", "Object Storage"],
                    "country": "GB",
                },
            ]
        )

        first = generate_region_policy_artifact(client=client)
        second = generate_region_policy_artifact(client=client)

        self.assertEqual(first, second)
        self.assertEqual(
            first,
            """# Generated by linode-image-lab region-policy generate.
# Version this provider policy snapshot and review diffs for provider drift.
# provider_regions.* and generated_groups.* are generated; provider_overrides.* is documented.
# groups.* is operator-owned intent.
schema_version = 1

[provider_regions.gb-lon]
capabilities = ["Linodes", "Object Storage"]

[provider_regions.us-sea]
capabilities = ["Linodes", "Object Storage"]

[generated_groups.capability_linodes]
regions = ["gb-lon", "us-sea"]

[generated_groups.capability_object_storage]
regions = ["gb-lon", "us-sea"]

[generated_groups.country_gb]
regions = ["gb-lon"]

[generated_groups.country_gb_image_replication]
regions = ["gb-lon"]

[generated_groups.country_gb_linodes]
regions = ["gb-lon"]

[generated_groups.country_gb_object_storage]
regions = ["gb-lon"]

[generated_groups.country_us]
regions = ["us-sea"]

[generated_groups.country_us_image_replication]
regions = ["us-sea"]

[generated_groups.country_us_linodes]
regions = ["us-sea"]

[generated_groups.country_us_object_storage]
regions = ["us-sea"]
""",
        )

    def test_country_capability_groups_include_only_matching_regions(self) -> None:
        groups = generated_region_groups(
            [
                {
                    "region": "us-east",
                    "capabilities": ["Linodes", "Object Storage"],
                    "country": "us",
                },
                {
                    "region": "us-west",
                    "capabilities": ["Linodes"],
                    "country": "us",
                },
                {
                    "region": "gb-lon",
                    "capabilities": ["Linodes", "Object Storage"],
                    "country": "gb",
                },
            ]
        )

        self.assertEqual(groups["country_us"], ["us-east", "us-west"])
        self.assertEqual(groups["country_us_linodes"], ["us-east", "us-west"])
        self.assertEqual(groups["country_us_object_storage"], ["us-east"])
        self.assertEqual(groups["country_us_image_replication"], ["us-east"])
        self.assertEqual(groups["country_gb_object_storage"], ["gb-lon"])
        self.assertEqual(groups["country_gb_image_replication"], ["gb-lon"])

    def test_image_replication_overrides_only_affect_image_replication_groups(self) -> None:
        provider_regions = [
            {
                "region": "de-fra-2",
                "capabilities": ["Linodes", "Object Storage"],
                "country": "de",
            },
            {
                "region": "us-east",
                "capabilities": ["Linodes", "Object Storage"],
                "country": "us",
            },
            {
                "region": "us-iad-2",
                "capabilities": ["Linodes", "Object Storage"],
                "country": "us",
            },
            {
                "region": "jp-tyo-3",
                "capabilities": ["Linodes", "Object Storage"],
                "country": "jp",
            },
            {
                "region": "us-west",
                "capabilities": ["Linodes"],
                "country": "us",
            },
        ]
        groups = generated_region_groups(
            provider_regions,
            provider_overrides={
                "image_replication_excluded_regions": {
                    "regions": ["de-fra-2", "jp-tyo-3", "us-iad-2"],
                    "reason": "provider discrepancy",
                }
            },
        )

        self.assertEqual(groups["country_de"], ["de-fra-2"])
        self.assertEqual(groups["country_de_object_storage"], ["de-fra-2"])
        self.assertNotIn("country_de_image_replication", groups)
        self.assertEqual(groups["country_jp"], ["jp-tyo-3"])
        self.assertEqual(groups["country_jp_object_storage"], ["jp-tyo-3"])
        self.assertNotIn("country_jp_image_replication", groups)
        self.assertEqual(groups["country_us"], ["us-east", "us-iad-2", "us-west"])
        self.assertEqual(groups["country_us_object_storage"], ["us-east", "us-iad-2"])
        self.assertEqual(groups["capability_object_storage"], ["de-fra-2", "jp-tyo-3", "us-east", "us-iad-2"])
        self.assertEqual(groups["country_us_image_replication"], ["us-east"])

    def test_country_capability_group_names_are_normalized(self) -> None:
        self.assertEqual(
            generated_country_capability_group_name("us", "Object Storage"),
            "country_us_object_storage",
        )
        self.assertEqual(
            generated_country_capability_group_name("gb", "ACLP Logs Datacenter LKE-E"),
            "country_gb_aclp_logs_datacenter_lke_e",
        )
        self.assertEqual(generated_country_capability_group_name(None, "Object Storage"), None)

    def test_generation_preserves_operator_groups_from_existing_policy(self) -> None:
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        policy_path = Path(directory.name) / "region-policy.toml"
        policy_path.write_text(
            """schema_version = 1
[provider_regions.old-region]
capabilities = ["Linodes"]
[groups.us]
regions = ["us-sea", "us-east"]
""",
            encoding="utf-8",
        )
        client = FakeRegionClient(
            [
                {"region": "us-east", "capabilities": ["Linodes"]},
                {"region": "us-sea", "capabilities": ["Linodes", "Object Storage"], "country": "us"},
            ]
        )

        artifact = generate_region_policy_artifact(client=client, existing_policy_path=policy_path)

        self.assertIn("[provider_regions.us-east]\ncapabilities = [\"Linodes\"]", artifact)
        self.assertIn("[generated_groups.capability_object_storage]\nregions = [\"us-sea\"]", artifact)
        self.assertIn("[generated_groups.country_us]\nregions = [\"us-sea\"]", artifact)
        self.assertIn("[generated_groups.country_us_object_storage]\nregions = [\"us-sea\"]", artifact)
        self.assertIn("[groups.us]\nregions = [\"us-sea\", \"us-east\"]", artifact)
        self.assertNotIn("old-region", artifact)

    def test_generation_can_explicitly_isolate_provider_sections(self) -> None:
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        policy_path = Path(directory.name) / "region-policy.toml"
        policy_path.write_text(
            """schema_version = 1
[provider_regions.us-east]
capabilities = ["Linodes"]
[groups.us]
regions = ["us-east"]
""",
            encoding="utf-8",
        )
        client = FakeRegionClient([{"region": "us-east", "capabilities": ["Linodes"]}])

        artifact = generate_region_policy_artifact(
            client=client,
            existing_policy_path=policy_path,
            replace_groups=True,
        )

        self.assertIn("[provider_regions.us-east]", artifact)
        self.assertIn("[generated_groups.capability_linodes]", artifact)
        self.assertNotIn("[groups.us]", artifact)

    def test_generation_overwrites_existing_generated_groups(self) -> None:
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        policy_path = Path(directory.name) / "region-policy.toml"
        policy_path.write_text(
            """schema_version = 1
[provider_regions.us-east]
capabilities = ["Linodes"]
[generated_groups.capability_linodes]
regions = ["stale-region"]
[groups.us]
regions = ["us-east"]
""",
            encoding="utf-8",
        )
        client = FakeRegionClient([{"region": "us-east", "capabilities": ["Linodes"], "country": "us"}])

        artifact = generate_region_policy_artifact(client=client, existing_policy_path=policy_path)

        self.assertIn("[generated_groups.capability_linodes]\nregions = [\"us-east\"]", artifact)
        self.assertIn("[generated_groups.country_us]\nregions = [\"us-east\"]", artifact)
        self.assertIn("[generated_groups.country_us_linodes]\nregions = [\"us-east\"]", artifact)
        self.assertIn("[groups.us]\nregions = [\"us-east\"]", artifact)
        self.assertNotIn("stale-region", artifact)

    def test_generation_overwrites_malformed_generated_groups(self) -> None:
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        policy_path = Path(directory.name) / "region-policy.toml"
        policy_path.write_text(
            """schema_version = 1
[provider_regions.us-east]
capabilities = ["Linodes"]
[generated_groups.capability_linodes]
unexpected = true
[groups.us]
regions = ["us-east"]
""",
            encoding="utf-8",
        )
        client = FakeRegionClient([{"region": "us-east", "capabilities": ["Linodes"], "country": "us"}])

        artifact = generate_region_policy_artifact(client=client, existing_policy_path=policy_path)

        self.assertIn("[generated_groups.capability_linodes]\nregions = [\"us-east\"]", artifact)
        self.assertIn("[groups.us]\nregions = [\"us-east\"]", artifact)
        self.assertNotIn("unexpected", artifact)

    def test_validation_accepts_current_policy(self) -> None:
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        policy_path = Path(directory.name) / "region-policy.toml"
        policy_path.write_text(
            """schema_version = 1
[provider_regions.us-east]
capabilities = ["Linodes", "Object Storage"]
[provider_regions.us-sea]
capabilities = ["Linodes"]
[generated_groups.capability_linodes]
regions = ["us-east", "us-sea"]
[generated_groups.capability_object_storage]
regions = ["us-east"]
[generated_groups.country_us]
regions = ["us-east", "us-sea"]
[generated_groups.country_us_image_replication]
regions = ["us-east"]
[generated_groups.country_us_linodes]
regions = ["us-east", "us-sea"]
[generated_groups.country_us_object_storage]
regions = ["us-east"]
[groups.us]
regions = ["us-sea", "us-east"]
""",
            encoding="utf-8",
        )
        client = FakeRegionClient(
            [
                {"region": "us-sea", "capabilities": ["Linodes"], "country": "us"},
                {"region": "us-east", "capabilities": ["Object Storage", "Linodes"], "country": "us"},
            ]
        )

        report = validate_region_policy_artifact(path=policy_path, client=client)

        self.assertTrue(report["valid"])
        self.assertEqual(report["errors"], [])
        self.assertEqual(report["provider_region_count"], 2)
        self.assertEqual(report["generated_group_count"], 6)
        self.assertEqual(report["group_count"], 1)

    def test_validation_accepts_image_replication_override_snapshot(self) -> None:
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        policy_path = Path(directory.name) / "region-policy.toml"
        policy_path.write_text(
            """schema_version = 1
[provider_regions.us-east]
capabilities = ["Linodes", "Object Storage"]
[provider_regions.us-iad-2]
capabilities = ["Linodes", "Object Storage"]
[provider_regions.jp-tyo-3]
capabilities = ["Linodes", "Object Storage"]
[provider_regions.de-fra-2]
capabilities = ["Linodes", "Object Storage"]
[provider_overrides.image_replication_excluded_regions]
regions = ["de-fra-2", "jp-tyo-3", "us-iad-2"]
reason = "Provider advertises Object Storage, but image replication rejects these regions."
[generated_groups.capability_linodes]
regions = ["de-fra-2", "jp-tyo-3", "us-east", "us-iad-2"]
[generated_groups.capability_object_storage]
regions = ["de-fra-2", "jp-tyo-3", "us-east", "us-iad-2"]
[generated_groups.country_de]
regions = ["de-fra-2"]
[generated_groups.country_de_linodes]
regions = ["de-fra-2"]
[generated_groups.country_de_object_storage]
regions = ["de-fra-2"]
[generated_groups.country_jp]
regions = ["jp-tyo-3"]
[generated_groups.country_jp_linodes]
regions = ["jp-tyo-3"]
[generated_groups.country_jp_object_storage]
regions = ["jp-tyo-3"]
[generated_groups.country_us]
regions = ["us-east", "us-iad-2"]
[generated_groups.country_us_image_replication]
regions = ["us-east"]
[generated_groups.country_us_linodes]
regions = ["us-east", "us-iad-2"]
[generated_groups.country_us_object_storage]
regions = ["us-east", "us-iad-2"]
""",
            encoding="utf-8",
        )
        client = FakeRegionClient(
            [
                {"region": "de-fra-2", "capabilities": ["Linodes", "Object Storage"], "country": "de"},
                {"region": "jp-tyo-3", "capabilities": ["Linodes", "Object Storage"], "country": "jp"},
                {"region": "us-east", "capabilities": ["Linodes", "Object Storage"], "country": "us"},
                {"region": "us-iad-2", "capabilities": ["Linodes", "Object Storage"], "country": "us"},
            ]
        )

        report = validate_region_policy_artifact(path=policy_path, client=client)

        self.assertTrue(report["valid"])
        self.assertEqual(report["errors"], [])

    def test_generation_preserves_overrides_and_raw_provider_facts(self) -> None:
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        policy_path = Path(directory.name) / "region-policy.toml"
        policy_path.write_text(
            """schema_version = 1
[provider_overrides.image_replication_excluded_regions]
regions = ["de-fra-2", "jp-tyo-3", "us-iad-2"]
reason = "Provider advertises Object Storage, but image replication rejects these regions."
""",
            encoding="utf-8",
        )
        client = FakeRegionClient(
            [
                {"region": "de-fra-2", "capabilities": ["Linodes", "Object Storage"], "country": "de"},
                {"region": "jp-tyo-3", "capabilities": ["Linodes", "Object Storage"], "country": "jp"},
                {"region": "us-east", "capabilities": ["Linodes", "Object Storage"], "country": "us"},
                {"region": "us-iad-2", "capabilities": ["Linodes", "Object Storage"], "country": "us"},
            ]
        )

        artifact = generate_region_policy_artifact(client=client, existing_policy_path=policy_path)
        second_artifact = generate_region_policy_artifact(client=client, existing_policy_path=policy_path)

        self.assertEqual(artifact, second_artifact)
        self.assertIn("[provider_regions.de-fra-2]\ncapabilities = [\"Linodes\", \"Object Storage\"]", artifact)
        self.assertIn("[provider_regions.jp-tyo-3]\ncapabilities = [\"Linodes\", \"Object Storage\"]", artifact)
        self.assertIn("[provider_regions.us-iad-2]\ncapabilities = [\"Linodes\", \"Object Storage\"]", artifact)
        self.assertIn("[provider_overrides.image_replication_excluded_regions]", artifact)
        self.assertIn("regions = [\"de-fra-2\", \"jp-tyo-3\", \"us-iad-2\"]", artifact)
        self.assertIn("[generated_groups.country_de_object_storage]\nregions = [\"de-fra-2\"]", artifact)
        self.assertNotIn("[generated_groups.country_de_image_replication]", artifact)
        self.assertIn("[generated_groups.country_jp_object_storage]\nregions = [\"jp-tyo-3\"]", artifact)
        self.assertNotIn("[generated_groups.country_jp_image_replication]", artifact)
        self.assertIn("[generated_groups.country_us_object_storage]\nregions = [\"us-east\", \"us-iad-2\"]", artifact)
        self.assertIn("[generated_groups.country_us_image_replication]\nregions = [\"us-east\"]", artifact)

    def test_validation_rejects_unknown_provider_region(self) -> None:
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        policy_path = Path(directory.name) / "region-policy.toml"
        policy_path.write_text(
            """schema_version = 1
[provider_regions.us-east]
capabilities = ["Linodes"]
[provider_regions.us-ghost]
capabilities = ["Linodes"]
[generated_groups.capability_linodes]
regions = ["us-east", "us-ghost"]
""",
            encoding="utf-8",
        )
        client = FakeRegionClient([{"region": "us-east", "capabilities": ["Linodes"]}])

        report = validate_region_policy_artifact(path=policy_path, client=client)

        self.assertFalse(report["valid"])
        self.assertIn("unknown_provider_region", {error["code"] for error in report["errors"]})

    def test_validation_rejects_group_referencing_unknown_region(self) -> None:
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        policy_path = Path(directory.name) / "region-policy.toml"
        policy_path.write_text(
            """schema_version = 1
[provider_regions.us-east]
capabilities = ["Linodes"]
[generated_groups.capability_linodes]
regions = ["us-east"]
[groups.us]
regions = ["us-east", "us-ghost"]
""",
            encoding="utf-8",
        )
        client = FakeRegionClient([{"region": "us-east", "capabilities": ["Linodes"]}])

        report = validate_region_policy_artifact(path=policy_path, client=client)

        self.assertFalse(report["valid"])
        self.assertEqual(report["errors"][0]["code"], "unknown_groups_region")

    def test_validation_rejects_generated_group_referencing_unknown_region(self) -> None:
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        policy_path = Path(directory.name) / "region-policy.toml"
        policy_path.write_text(
            """schema_version = 1
[provider_regions.us-east]
capabilities = ["Linodes"]
[generated_groups.capability_linodes]
regions = ["us-east", "us-ghost"]
""",
            encoding="utf-8",
        )
        client = FakeRegionClient([{"region": "us-east", "capabilities": ["Linodes"]}])

        report = validate_region_policy_artifact(path=policy_path, client=client)

        self.assertFalse(report["valid"])
        self.assertEqual(report["errors"][0]["code"], "unknown_generated_groups_region")

    def test_validation_rejects_stale_provider_capabilities(self) -> None:
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        policy_path = Path(directory.name) / "region-policy.toml"
        policy_path.write_text(
            """schema_version = 1
[provider_regions.us-east]
capabilities = ["Linodes"]
[generated_groups.capability_linodes]
regions = ["us-east"]
""",
            encoding="utf-8",
        )
        client = FakeRegionClient([{"region": "us-east", "capabilities": ["Linodes", "Object Storage"]}])

        report = validate_region_policy_artifact(path=policy_path, client=client)

        self.assertFalse(report["valid"])
        self.assertEqual(report["errors"][0]["code"], "stale_provider_capabilities")

    def test_validation_rejects_malformed_policy(self) -> None:
        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        policy_path = Path(directory.name) / "region-policy.toml"
        policy_path.write_text("schema_version =\n", encoding="utf-8")
        client = FakeRegionClient([{"region": "us-east", "capabilities": ["Linodes"]}])

        report = validate_region_policy_artifact(path=policy_path, client=client)

        self.assertFalse(report["valid"])
        self.assertEqual(report["errors"][0]["code"], "malformed_policy")

    def test_validation_output_is_public_safe(self) -> None:
        report = {
            "schema_version": 1,
            "command": "region-policy",
            "action": "validate",
            "path": "policy/region-policy.toml",
            "valid": True,
            "status": "valid",
            "safety": {"mutates": False, "account_data": "not_read"},
            "errors": [],
        }

        serialized = serialize_validation_report(report)
        payload = json.loads(serialized)

        self.assertEqual(payload["safety"]["account_data"], "not_read")
        self.assertNotIn("LINODE_TOKEN", serialized)
        self.assertNotIn("private/", serialized)
